logging:
  level:
    tk.mybatis: DEBUG
    hzqing.com.blogadmin: DEBUG
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/blog_admin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
      database: 0
      host: localhost
      pool:
        max-active: 20
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: hzqing.com.blogadmin
server:
  port: 8899
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
blog:
  images:
    path: ${CFG_BLOG_IMG_PATH:/home/hzq/hblog/}
debug: true
